spring:
  datasource:
    url: jdbc:h2:mem:mvc-crud
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

jwt:
  secret: "this-is-a-very-long-secret-key-for-jwt-token-signing-practice-2026"
  access-token-validity-in-seconds: 3600
